const jsonArrays = [
  {
    id: 18,
    merchant_id: 6,
    seq: 451,
    program_name: 'HKD_P17_DISTRIBUTION',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P17", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P17", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P17", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 1,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail: 'https://static.prod.pfh-in.com/app/Futurecard.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2024-03-22T10:55:44.658Z',
    last_modified_by: 'auto',
    last_modified_date: '2024-03-22T10:55:44.658Z',
    vip_level: null,
  },
  {
    id: 41,
    merchant_id: 6,
    seq: 351,
    program_name: 'HKD_P28_DISTRIBUTION',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P28", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P28", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P28", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 1,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail: 'https://static.prod.pfh-in.com/app/Futurecard.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2024-05-23T01:53:11.762Z',
    last_modified_by: 'auto',
    last_modified_date: '2024-05-23T01:53:11.762Z',
    vip_level: null,
  },
  {
    id: 14,
    merchant_id: 6,
    seq: 352,
    program_name: 'HKD_P31_DISTRIBUTION',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P31", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P31", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P31", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 1,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail: 'https://static.prod.pfh-in.com/app/Futurecard.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2024-03-20T06:27:31.561Z',
    last_modified_by: 'auto',
    last_modified_date: '2024-03-20T06:27:31.561Z',
    vip_level: null,
  },
  {
    id: 73,
    merchant_id: 6,
    seq: 301,
    program_name: 'HKD_P53_DISTRIBUTION',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P53", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P53", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P53", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 5,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail: 'https://static.prod.pfh-in.com/app/TitanCard.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2024-08-16T04:01:36.101Z',
    last_modified_by: 'auto',
    last_modified_date: '2024-08-16T04:01:36.101Z',
    vip_level: 1,
  },
  {
    id: 58,
    merchant_id: 6,
    seq: 302,
    program_name: 'HKD_P57_DISTRIBUTION',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P57", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P57", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P57", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 5,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail: 'https://static.prod.pfh-in.com/app/TitanCard.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2024-06-19T07:00:09.539Z',
    last_modified_by: 'auto',
    last_modified_date: '2024-06-19T07:00:09.539Z',
    vip_level: 1,
  },
  {
    id: 61,
    merchant_id: 6,
    seq: 851,
    program_name: 'HKD_P60_DISTRIBUTION',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P60", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P60", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P60", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 4,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail:
      'https://static.prod.pfh-in.com/app/ProsperousCard.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2024-06-26T08:16:46.829Z',
    last_modified_by: 'auto',
    last_modified_date: '2024-06-26T08:16:46.829Z',
    vip_level: null,
  },
  {
    id: 22,
    merchant_id: 6,
    seq: 353,
    program_name: 'HKD_P72_DISTRIBUTION',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P72", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P72", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P72", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 1,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail: 'https://static.prod.pfh-in.com/app/Futurecard.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2024-03-22T10:55:44.658Z',
    last_modified_by: 'auto',
    last_modified_date: '2024-03-22T10:55:44.658Z',
    vip_level: null,
  },
  {
    id: 66,
    merchant_id: 6,
    seq: 354,
    program_name: 'HKD_P73_DISTRIBUTION',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P73", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P73", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P73", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 4,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail:
      'https://static.prod.pfh-in.com/app/ProsperousCard.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2024-07-05T11:32:09.677Z',
    last_modified_by: 'auto',
    last_modified_date: '2024-07-05T11:32:09.677Z',
    vip_level: null,
  },
  {
    id: 76,
    merchant_id: 6,
    seq: 355,
    program_name: 'HKD_P75_DISTRIBUTION',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P75", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P75", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P75", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 4,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail:
      'https://static.prod.pfh-in.com/app/ProsperousCard.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2024-09-12T10:53:48.941Z',
    last_modified_by: 'auto',
    last_modified_date: '2024-09-12T10:53:48.941Z',
    vip_level: null,
  },
  {
    id: 146,
    merchant_id: 6,
    seq: 366,
    program_name: 'VGL-E003-BLUEP272',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://double-pay.com/", "cardName": "BLUEP272", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/gl_water_mark.png"}, {"linkUrl": "https://double-pay.com/", "cardName": "BLUEP272", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/gl_water_mark.png"}, {"linkUrl": "https://double-pay.com/", "cardName": "BLUEP272", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/gl_water_mark.png"}]',
    layout: 3,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/gl_water_mark.png',
    background_thumbnail: 'https://static.prod.pfh-in.com/app/BluePlatinum.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2025-03-20T09:20:19.012Z',
    last_modified_by: 'auto',
    last_modified_date: '2025-03-20T09:20:19.012Z',
    vip_level: null,
  },
  {
    id: 121,
    merchant_id: 6,
    seq: 356,
    program_name: 'VGL-E003-BLUEP28',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://double-pay.com/", "cardName": "BLUEP28", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://double-pay.com/", "cardName": "BLUEP28", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://double-pay.com/", "cardName": "BLUEP28", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 3,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail: 'https://static.prod.pfh-in.com/app/BluePlatinum.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2025-01-21T10:15:18.304Z',
    last_modified_by: 'auto',
    last_modified_date: '2025-01-21T10:15:18.304Z',
    vip_level: null,
  },
  {
    id: 131,
    merchant_id: 6,
    seq: 357,
    program_name: 'VGL-E003-RGP271',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://double-pay.com/", "cardName": "RGP271", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/gl_water_mark.png"}, {"linkUrl": "https://double-pay.com/", "cardName": "RGP271", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/gl_water_mark.png"}, {"linkUrl": "https://double-pay.com/", "cardName": "RGP271", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/gl_water_mark.png"}]',
    layout: 1,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/gl_water_mark.png',
    background_thumbnail:
      'https://static.prod.pfh-in.com/app/GoldenLeasingRoseGoldPlatinum.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2025-02-18T09:57:13.752Z',
    last_modified_by: 'auto',
    last_modified_date: '2025-02-18T09:57:13.752Z',
    vip_level: null,
  },
  {
    id: 122,
    merchant_id: 6,
    seq: 358,
    program_name: 'VGL-E003-RGP73',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://double-pay.com/", "cardName": "RGP73", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/gl_water_mark.png"}, {"linkUrl": "https://double-pay.com/", "cardName": "RGP73", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/gl_water_mark.png"}, {"linkUrl": "https://double-pay.com/", "cardName": "RGP73", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/gl_water_mark.png"}]',
    layout: 1,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/gl_water_mark.png',
    background_thumbnail:
      'https://static.prod.pfh-in.com/app/GoldenLeasingRoseGoldPlatinum.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2025-01-22T04:48:36.264Z',
    last_modified_by: 'auto',
    last_modified_date: '2025-01-22T04:48:36.264Z',
    vip_level: null,
  },
  {
    id: 106,
    merchant_id: 6,
    seq: 852,
    program_name: 'VGL-E008-BLUEP02',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "BLUEP02", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "BLUEP02", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "BLUEP02", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 3,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail: 'https://static.prod.pfh-in.com/app/BluePlatinum.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2024-12-20T07:29:42.632Z',
    last_modified_by: 'auto',
    last_modified_date: '2024-12-20T07:29:42.632Z',
    vip_level: null,
  },
  {
    id: 107,
    merchant_id: 6,
    seq: 853,
    program_name: 'VGL-E008-BLUEP03',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "BLUEP03", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "BLUEP03", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "BLUEP03", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 3,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail: 'https://static.prod.pfh-in.com/app/BluePlatinum.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2024-12-20T07:29:42.632Z',
    last_modified_by: 'auto',
    last_modified_date: '2024-12-20T07:29:42.632Z',
    vip_level: null,
  },
  {
    id: 94,
    merchant_id: 6,
    seq: 359,
    program_name: 'VProsperous-E003-P44',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P44", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P44", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P44", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 4,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail:
      'https://static.prod.pfh-in.com/app/ProsperousCard.png',
    logo: 'https://static.prod.pfh-in.com/app/pfh_logo_white.png',
    created_by: 'auto',
    created_date: '2024-11-14T01:16:59.137Z',
    last_modified_by: 'auto',
    last_modified_date: '2024-11-14T01:16:59.137Z',
    vip_level: null,
  },
  {
    id: 81,
    merchant_id: 6,
    seq: 361,
    program_name: 'VProsperous-E003-P63',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P63", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P63", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P63", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 4,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail:
      'https://static.prod.pfh-in.com/app/ProsperousCard.png',
    logo: 'https://static.prod.pfh-in.com/app/pfh_logo_white.png',
    created_by: 'auto',
    created_date: '2024-10-25T01:35:39.632Z',
    last_modified_by: 'auto',
    last_modified_date: '2024-10-25T01:35:39.632Z',
    vip_level: null,
  },
  {
    id: 88,
    merchant_id: 6,
    seq: 362,
    program_name: 'VProsperous-E003-P64',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P64", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P64", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P64", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 4,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail:
      'https://static.prod.pfh-in.com/app/ProsperousCard.png',
    logo: 'https://static.prod.pfh-in.com/app/pfh_logo_white.png',
    created_by: 'auto',
    created_date: '2024-11-05T11:04:30.851Z',
    last_modified_by: 'auto',
    last_modified_date: '2024-11-05T11:04:30.851Z',
    vip_level: null,
  },
  {
    id: 91,
    merchant_id: 6,
    seq: 363,
    program_name: 'VProsperous-E003-P67',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P67", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P67", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P67", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 4,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail:
      'https://static.prod.pfh-in.com/app/ProsperousCard.png',
    logo: 'https://static.prod.pfh-in.com/app/pfh_logo_white.png',
    created_by: 'auto',
    created_date: '2024-11-14T01:16:59.137Z',
    last_modified_by: 'auto',
    last_modified_date: '2024-11-14T01:16:59.137Z',
    vip_level: null,
  },
  {
    id: 92,
    merchant_id: 6,
    seq: 364,
    program_name: 'VProsperous-E003-P68',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P68", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P68", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P68", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 4,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail:
      'https://static.prod.pfh-in.com/app/ProsperousCard.png',
    logo: 'https://static.prod.pfh-in.com/app/pfh_logo_white.png',
    created_by: 'auto',
    created_date: '2024-11-14T01:16:59.137Z',
    last_modified_by: 'auto',
    last_modified_date: '2024-11-14T01:16:59.137Z',
    vip_level: null,
  },
  {
    id: 93,
    merchant_id: 6,
    seq: 365,
    program_name: 'VProsperous-E003-P69',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P69", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P69", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P69", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 4,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail:
      'https://static.prod.pfh-in.com/app/ProsperousCard.png',
    logo: 'https://static.prod.pfh-in.com/app/pfh_logo_white.png',
    created_by: 'auto',
    created_date: '2024-11-14T01:16:59.137Z',
    last_modified_by: 'auto',
    last_modified_date: '2024-11-14T01:16:59.137Z',
    vip_level: null,
  },
  {
    id: 90,
    merchant_id: 6,
    seq: 1599,
    program_name: 'VProsperous-E013-P65',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P65", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P65", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P65", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 4,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail:
      'https://static.prod.pfh-in.com/app/ProsperousCard.png',
    logo: 'https://static.prod.pfh-in.com/app/pfh_logo_white.png',
    created_by: 'auto',
    created_date: '2024-11-06T10:13:03.011Z',
    last_modified_by: 'auto',
    last_modified_date: '2024-11-06T10:13:03.011Z',
    vip_level: null,
  },
  {
    id: 125,
    merchant_id: 6,
    seq: 1551,
    program_name: 'VProsperous-E015-P65',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P65", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P65", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P65", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 4,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail:
      'https://static.prod.pfh-in.com/app/ProsperousCard.png',
    logo: 'https://static.prod.pfh-in.com/app/pfh_logo_white.png',
    created_by: 'auto',
    created_date: '2025-02-05T02:15:13.679Z',
    last_modified_by: 'auto',
    last_modified_date: '2025-02-05T02:15:13.679Z',
    vip_level: null,
  },
  {
    id: 100,
    merchant_id: 6,
    seq: 303,
    program_name: 'VTitan-E003-P90',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P90", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P90", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P90", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 5,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail: 'https://static.prod.pfh-in.com/app/TitanCard.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2024-11-22T11:59:59.132Z',
    last_modified_by: 'auto',
    last_modified_date: '2024-11-22T11:59:59.132Z',
    vip_level: 1,
  },
  {
    id: 103,
    merchant_id: 6,
    seq: 801,
    program_name: 'VTitan-E008-P51',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P51", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P51", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P51", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 5,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail: 'https://static.prod.pfh-in.com/app/TitanCard.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2024-12-17T08:10:44.378Z',
    last_modified_by: 'auto',
    last_modified_date: '2024-12-17T08:10:44.378Z',
    vip_level: 1,
  },
  {
    id: 104,
    merchant_id: 6,
    seq: 802,
    program_name: 'VTitan-E008-P52',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P52", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P52", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P52", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 5,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail: 'https://static.prod.pfh-in.com/app/TitanCard.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2024-12-17T08:10:44.378Z',
    last_modified_by: 'auto',
    last_modified_date: '2024-12-17T08:10:44.378Z',
    vip_level: 1,
  },
  {
    id: 102,
    merchant_id: 6,
    seq: 803,
    program_name: 'VTitan-E008-P90',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P90", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P90", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P90", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 5,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail: 'https://static.prod.pfh-in.com/app/TitanCard.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2024-12-17T08:10:44.378Z',
    last_modified_by: 'auto',
    last_modified_date: '2024-12-17T08:10:44.378Z',
    vip_level: 1,
  },
  {
    id: 75,
    merchant_id: 6,
    seq: 804,
    program_name: 'VTP36-E008-T55',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P55", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P55", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P55", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 5,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail: 'https://static.prod.pfh-in.com/app/TitanCard.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2024-09-11T11:10:45.621Z',
    last_modified_by: 'auto',
    last_modified_date: '2024-09-11T11:10:45.621Z',
    vip_level: 1,
  },
  {
    id: 87,
    merchant_id: 6,
    seq: 304,
    program_name: 'VTP57-E003-TP72',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "TP72", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "TP72", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "TP72", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 5,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail: 'https://static.prod.pfh-in.com/app/TitanCard.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2024-10-31T11:34:18.372Z',
    last_modified_by: 'auto',
    last_modified_date: '2024-10-31T11:34:18.372Z',
    vip_level: 1,
  },
];

for (const jsonArray of jsonArrays) {
  const cardInfos = JSON.parse(jsonArray.card_infos);

  for (const cardInfo of cardInfos) {
    cardInfo.linkUrl = 'https://double-pay.com/';
    cardInfo.watermarkUrl =
      'https://static.prod.pfh-in.com/app/gl_water_mark.png';
  }

  const sql = `-- ${jsonArray.program_name}
update pmp_access.merchant_program_configs
set
  card_infos = '${JSON.stringify(cardInfos)}',
  background = 'https://static.prod.pfh-in.com/app/gl_water_mark.png',
  logo = 'https://static.prod.pfh-in.com/app/dp_logo_black.png',
  last_modified_date = now ()
where
  id = '${jsonArray.id}'
  and program_name = '${jsonArray.program_name}';\n`;

  console.log(`${sql}`);
}
