const jsonArray = [
  {
    id: 53,
    merchant_id: 6,
    seq: 601,
    program_name: 'HKD_P36_DISTRIBUTION',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P36", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P36", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P36", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 5,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail: 'https://static.prod.pfh-in.com/app/TitanCard.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2024-06-04T10:40:52.007Z',
    last_modified_by: 'auto',
    last_modified_date: '2024-06-04T10:40:52.007Z',
    vip_level: 1,
  },
  {
    id: 59,
    merchant_id: 6,
    seq: 651,
    program_name: 'HKD_P37_DISTRIBUTION',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P37", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P37", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P37", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 4,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail:
      'https://static.prod.pfh-in.com/app/ProsperousCard.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2024-06-20T09:18:26.007Z',
    last_modified_by: 'auto',
    last_modified_date: '2024-06-20T09:18:26.007Z',
    vip_level: null,
  },
  {
    id: 60,
    merchant_id: 6,
    seq: 652,
    program_name: 'HKD_P38_DISTRIBUTION',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P38", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P38", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P38", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 4,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail:
      'https://static.prod.pfh-in.com/app/ProsperousCard.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2024-06-26T08:16:46.829Z',
    last_modified_by: 'auto',
    last_modified_date: '2024-06-26T08:16:46.829Z',
    vip_level: null,
  },
  {
    id: 63,
    merchant_id: 6,
    seq: 653,
    program_name: 'HKD_P39_DISTRIBUTION',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P39", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P39", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P39", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 4,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail:
      'https://static.prod.pfh-in.com/app/ProsperousCard.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2024-06-28T03:03:59.604Z',
    last_modified_by: 'auto',
    last_modified_date: '2024-06-28T03:03:59.604Z',
    vip_level: null,
  },
  {
    id: 62,
    merchant_id: 6,
    seq: 653,
    program_name: 'HKD_P39_DISTRIBUTION',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P39", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P39", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P39", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 4,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail:
      'https://static.prod.pfh-in.com/app/ProsperousCard.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2024-06-28T02:44:51.612Z',
    last_modified_by: 'auto',
    last_modified_date: '2024-06-28T02:44:51.612Z',
    vip_level: null,
  },
  {
    id: 74,
    merchant_id: 6,
    seq: 603,
    program_name: 'HKD_P54_DISTRIBUTION',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P54", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P54", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P54", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 5,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail: 'https://static.prod.pfh-in.com/app/TitanCard.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2024-08-27T06:09:47.291Z',
    last_modified_by: 'auto',
    last_modified_date: '2024-08-27T06:09:47.291Z',
    vip_level: 1,
  },
  {
    id: 64,
    merchant_id: 6,
    seq: 951,
    program_name: 'HKD_P61_DISTRIBUTION',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P61", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P61", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P61", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 4,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail:
      'https://static.prod.pfh-in.com/app/ProsperousCard.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2024-07-04T09:58:57.081Z',
    last_modified_by: 'auto',
    last_modified_date: '2024-07-04T09:58:57.081Z',
    vip_level: null,
  },
  {
    id: 65,
    merchant_id: 6,
    seq: 1051,
    program_name: 'HKD_P62_DISTRIBUTION',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P62", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P62", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P62", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 4,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail:
      'https://static.prod.pfh-in.com/app/ProsperousCard.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2024-07-04T09:58:57.081Z',
    last_modified_by: 'auto',
    last_modified_date: '2024-07-04T09:58:57.081Z',
    vip_level: null,
  },
  {
    id: 67,
    merchant_id: 6,
    seq: 654,
    program_name: 'HKD_P70_DISTRIBUTION',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P70", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P70", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P70", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 4,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail:
      'https://static.prod.pfh-in.com/app/ProsperousCard.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2024-07-09T09:09:17.990Z',
    last_modified_by: 'auto',
    last_modified_date: '2024-07-09T09:09:17.990Z',
    vip_level: null,
  },
  {
    id: 69,
    merchant_id: 6,
    seq: 903,
    program_name: 'HKD_P82_DISTRIBUTION',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P82", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P82", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P82", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 5,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail: 'https://static.prod.pfh-in.com/app/TitanCard.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2024-07-12T09:54:29.235Z',
    last_modified_by: 'auto',
    last_modified_date: '2024-07-12T09:54:29.235Z',
    vip_level: 1,
  },
  {
    id: 70,
    merchant_id: 6,
    seq: 1001,
    program_name: 'HKD_P83_DISTRIBUTION',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P83", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P83", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P83", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 5,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail: 'https://static.prod.pfh-in.com/app/TitanCard.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2024-07-12T09:54:29.235Z',
    last_modified_by: 'auto',
    last_modified_date: '2024-07-12T09:54:29.235Z',
    vip_level: 1,
  },
  {
    id: 72,
    merchant_id: 6,
    seq: 602,
    program_name: 'HKD_P84_DISTRIBUTION',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P84", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P84", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P84", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 5,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail: 'https://static.prod.pfh-in.com/app/TitanCard.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2024-08-05T10:07:57.089Z',
    last_modified_by: 'auto',
    last_modified_date: '2024-08-05T10:07:57.089Z',
    vip_level: 1,
  },
  {
    id: 114,
    merchant_id: 6,
    seq: 656,
    program_name: 'VGL-E006-BLUEP06',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://double-pay.com/", "cardName": "BLUEP06", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://double-pay.com/", "cardName": "BLUEP06", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://double-pay.com/", "cardName": "BLUEP06", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 3,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail: 'https://static.prod.pfh-in.com/app/BluePlatinum.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2025-01-03T05:29:06.354Z',
    last_modified_by: 'auto',
    last_modified_date: '2025-01-03T05:29:06.354Z',
    vip_level: null,
  },
  {
    id: 116,
    merchant_id: 6,
    seq: 657,
    program_name: 'VGL-E006-BLUEP07',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://double-pay.com/", "cardName": "BLUEP07", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://double-pay.com/", "cardName": "BLUEP07", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://double-pay.com/", "cardName": "BLUEP07", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 3,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail: 'https://static.prod.pfh-in.com/app/BluePlatinum.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2025-01-06T09:57:56.329Z',
    last_modified_by: 'auto',
    last_modified_date: '2025-01-06T09:57:56.329Z',
    vip_level: null,
  },
  {
    id: 118,
    merchant_id: 6,
    seq: 658,
    program_name: 'VGL-E006-BLUEP08',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://double-pay.com/", "cardName": "BLUEP08", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://double-pay.com/", "cardName": "BLUEP08", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://double-pay.com/", "cardName": "BLUEP08", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 3,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail: 'https://static.prod.pfh-in.com/app/BluePlatinum.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2025-01-06T10:00:08.745Z',
    last_modified_by: 'auto',
    last_modified_date: '2025-01-06T10:00:08.745Z',
    vip_level: null,
  },
  {
    id: 120,
    merchant_id: 6,
    seq: 659,
    program_name: 'VGL-E006-BLUEP09',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://double-pay.com/", "cardName": "BLUEP09", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://double-pay.com/", "cardName": "BLUEP09", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://double-pay.com/", "cardName": "BLUEP09", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 3,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail: 'https://static.prod.pfh-in.com/app/BluePlatinum.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2025-01-21T10:15:18.304Z',
    last_modified_by: 'auto',
    last_modified_date: '2025-01-21T10:15:18.304Z',
    vip_level: null,
  },
  {
    id: 135,
    merchant_id: 6,
    seq: 660,
    program_name: 'VGL-E006-BLUEP291',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://double-pay.com/", "cardName": "BLUEP291", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/gl_water_mark.png"}, {"linkUrl": "https://double-pay.com/", "cardName": "BLUEP291", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/gl_water_mark.png"}, {"linkUrl": "https://double-pay.com/", "cardName": "BLUEP291", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/gl_water_mark.png"}]',
    layout: 3,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/gl_water_mark.png',
    background_thumbnail: 'https://static.prod.pfh-in.com/app/BluePlatinum.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2025-02-24T09:40:51.461Z',
    last_modified_by: 'auto',
    last_modified_date: '2025-02-24T09:40:51.461Z',
    vip_level: null,
  },
  {
    id: 124,
    merchant_id: 6,
    seq: 661,
    program_name: 'VGL-E006-BLUEP38',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://double-pay.com/", "cardName": "BLUEP38", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://double-pay.com/", "cardName": "BLUEP38", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://double-pay.com/", "cardName": "BLUEP38", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 3,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail: 'https://static.prod.pfh-in.com/app/BluePlatinum.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2025-02-04T02:42:08.018Z',
    last_modified_by: 'auto',
    last_modified_date: '2025-02-04T02:42:08.018Z',
    vip_level: null,
  },
  {
    id: 161,
    merchant_id: 6,
    seq: 663,
    program_name: 'VGL-E006-PURPLEP292',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://double-pay.com/", "cardName": "PURPLEP292", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/gl_water_mark.png"}, {"linkUrl": "https://double-pay.com/", "cardName": "PURPLEP292", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/gl_water_mark.png"}, {"linkUrl": "https://double-pay.com/", "cardName": "PURPLEP292", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/gl_water_mark.png"}]',
    layout: 3,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/gl_water_mark.png',
    background_thumbnail:
      'https://static.prod.pfh-in.com/app/GLPupplePlatinum.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2025-04-08T03:11:00.089Z',
    last_modified_by: 'auto',
    last_modified_date: '2025-04-08T03:11:00.089Z',
    vip_level: null,
  },
  {
    id: 160,
    merchant_id: 6,
    seq: 957,
    program_name: 'VGL-E009-BLUEP614',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://double-pay.com/", "cardName": "BLUEP614", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/gl_water_mark.png"}, {"linkUrl": "https://double-pay.com/", "cardName": "BLUEP614", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/gl_water_mark.png"}, {"linkUrl": "https://double-pay.com/", "cardName": "BLUEP614", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/gl_water_mark.png"}]',
    layout: 3,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/gl_water_mark.png',
    background_thumbnail: 'https://static.prod.pfh-in.com/app/BluePlatinum.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2025-04-08T03:11:00.089Z',
    last_modified_by: 'auto',
    last_modified_date: '2025-04-08T03:11:00.089Z',
    vip_level: null,
  },
  {
    id: 142,
    merchant_id: 6,
    seq: 956,
    program_name: 'VGL-E009-GREENP613',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://double-pay.com/", "cardName": "GREENP613", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/gl_water_mark.png"}, {"linkUrl": "https://double-pay.com/", "cardName": "GREENP613", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/gl_water_mark.png"}, {"linkUrl": "https://double-pay.com/", "cardName": "GREENP613", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/gl_water_mark.png"}]',
    layout: 3,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/gl_water_mark.png',
    background_thumbnail:
      'https://static.prod.pfh-in.com/app/GLGreenPlatinum.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2025-03-17T10:35:20.935Z',
    last_modified_by: 'auto',
    last_modified_date: '2025-03-17T10:35:20.935Z',
    vip_level: null,
  },
  {
    id: 141,
    merchant_id: 6,
    seq: 954,
    program_name: 'VGL-E009-PURPLEP611',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://double-pay.com/", "cardName": "PURPLEP611", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/gl_water_mark.png"}, {"linkUrl": "https://double-pay.com/", "cardName": "PURPLEP611", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/gl_water_mark.png"}, {"linkUrl": "https://double-pay.com/", "cardName": "PURPLEP611", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/gl_water_mark.png"}]',
    layout: 3,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/gl_water_mark.png',
    background_thumbnail:
      'https://static.prod.pfh-in.com/app/GLPupplePlatinum.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2025-03-17T10:35:20.935Z',
    last_modified_by: 'auto',
    last_modified_date: '2025-03-17T10:35:20.935Z',
    vip_level: null,
  },
  {
    id: 140,
    merchant_id: 6,
    seq: 955,
    program_name: 'VGL-E009-RGP612',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://double-pay.com/", "cardName": "RGP612", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/gl_water_mark.png"}, {"linkUrl": "https://double-pay.com/", "cardName": "RGP612", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/gl_water_mark.png"}, {"linkUrl": "https://double-pay.com/", "cardName": "RGP612", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/gl_water_mark.png"}]',
    layout: 3,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/gl_water_mark.png',
    background_thumbnail:
      'https://static.prod.pfh-in.com/app/GoldenLeasingRoseGoldPlatinum.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2025-03-17T10:35:20.935Z',
    last_modified_by: 'auto',
    last_modified_date: '2025-03-17T10:35:20.935Z',
    vip_level: null,
  },
  {
    id: 79,
    merchant_id: 6,
    seq: 662,
    program_name: 'VProsperous-E006-P79',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P79", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P79", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P79", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 4,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail:
      'https://static.prod.pfh-in.com/app/ProsperousCard.png',
    logo: 'https://static.prod.pfh-in.com/app/pfh_logo_white.png',
    created_by: 'auto',
    created_date: '2024-09-25T08:52:22.187Z',
    last_modified_by: 'auto',
    last_modified_date: '2024-09-25T08:52:22.187Z',
    vip_level: null,
  },
  {
    id: 97,
    merchant_id: 6,
    seq: 952,
    program_name: 'VProsperous-E009-PP77',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "PP77", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "PP77", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "PP77", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 4,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail:
      'https://static.prod.pfh-in.com/app/ProsperousCard.png',
    logo: 'https://static.prod.pfh-in.com/app/pfh_logo_white.png',
    created_by: 'auto',
    created_date: '2024-11-20T06:10:46.571Z',
    last_modified_by: 'auto',
    last_modified_date: '2024-11-20T06:10:46.571Z',
    vip_level: null,
  },
  {
    id: 98,
    merchant_id: 6,
    seq: 953,
    program_name: 'VProsperous-E009-PP78',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "PP78", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "PP78", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "PP78", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 4,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail:
      'https://static.prod.pfh-in.com/app/ProsperousCard.png',
    logo: 'https://static.prod.pfh-in.com/app/pfh_logo_white.png',
    created_by: 'auto',
    created_date: '2024-11-20T06:10:46.571Z',
    last_modified_by: 'auto',
    last_modified_date: '2024-11-20T06:10:46.571Z',
    vip_level: null,
  },
  {
    id: 117,
    merchant_id: 6,
    seq: 606,
    program_name: 'VTitan-E006-P91',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P91", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P91", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P91", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 3,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail: 'https://static.prod.pfh-in.com/app/TitanCard.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2025-01-06T09:59:12.523Z',
    last_modified_by: 'auto',
    last_modified_date: '2025-01-06T09:59:12.523Z',
    vip_level: null,
  },
  {
    id: 119,
    merchant_id: 6,
    seq: 604,
    program_name: 'VTitan-E006-P92',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://double-pay.com/", "cardName": "P92", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://double-pay.com/", "cardName": "P92", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://double-pay.com/", "cardName": "P92", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 5,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail: 'https://static.prod.pfh-in.com/app/TitanCard.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2025-01-21T10:15:18.304Z',
    last_modified_by: 'auto',
    last_modified_date: '2025-01-21T10:15:18.304Z',
    vip_level: 1,
  },
  {
    id: 95,
    merchant_id: 6,
    seq: 901,
    program_name: 'VTitan-E009-P86',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P86", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P86", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P86", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 5,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail: 'https://static.prod.pfh-in.com/app/TitanCard.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2024-11-20T06:10:46.571Z',
    last_modified_by: 'auto',
    last_modified_date: '2024-11-20T06:10:46.571Z',
    vip_level: 1,
  },
  {
    id: 143,
    merchant_id: 6,
    seq: 904,
    program_name: 'VTitan-E009-P861',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://double-pay.com/", "cardName": "P861", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/gl_water_mark.png"}, {"linkUrl": "https://double-pay.com/", "cardName": "P861", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/gl_water_mark.png"}, {"linkUrl": "https://double-pay.com/", "cardName": "P861", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/gl_water_mark.png"}]',
    layout: 5,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/gl_water_mark.png',
    background_thumbnail: 'https://static.prod.pfh-in.com/app/TitanCard.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2025-03-17T10:35:20.935Z',
    last_modified_by: 'auto',
    last_modified_date: '2025-03-17T10:35:20.935Z',
    vip_level: 1,
  },
  {
    id: 144,
    merchant_id: 6,
    seq: 905,
    program_name: 'VTitan-E009-P862',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://double-pay.com/", "cardName": "P862", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/gl_water_mark.png"}, {"linkUrl": "https://double-pay.com/", "cardName": "P862", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/gl_water_mark.png"}, {"linkUrl": "https://double-pay.com/", "cardName": "P862", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/gl_water_mark.png"}]',
    layout: 5,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/gl_water_mark.png',
    background_thumbnail: 'https://static.prod.pfh-in.com/app/TitanCard.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2025-03-17T10:35:20.935Z',
    last_modified_by: 'auto',
    last_modified_date: '2025-03-17T10:35:20.935Z',
    vip_level: 1,
  },
  {
    id: 145,
    merchant_id: 6,
    seq: 906,
    program_name: 'VTitan-E009-P863',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://double-pay.com/", "cardName": "P863", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/gl_water_mark.png"}, {"linkUrl": "https://double-pay.com/", "cardName": "P863", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/gl_water_mark.png"}, {"linkUrl": "https://double-pay.com/", "cardName": "P863", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/gl_water_mark.png"}]',
    layout: 5,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/gl_water_mark.png',
    background_thumbnail: 'https://static.prod.pfh-in.com/app/TitanCard.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2025-03-17T10:35:20.935Z',
    last_modified_by: 'auto',
    last_modified_date: '2025-03-17T10:35:20.935Z',
    vip_level: 1,
  },
  {
    id: 96,
    merchant_id: 6,
    seq: 902,
    program_name: 'VTitan-E009-P87',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P87", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P87", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P87", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 5,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail: 'https://static.prod.pfh-in.com/app/TitanCard.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2024-11-20T06:10:46.571Z',
    last_modified_by: 'auto',
    last_modified_date: '2024-11-20T06:10:46.571Z',
    vip_level: 1,
  },
  {
    id: 80,
    merchant_id: 6,
    seq: 605,
    program_name: 'VTP36-E006-P85',
    default: false,
    default_referral_code: null,
    card_infos:
      '[{"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P85", "language": "en", "linkName": "More details", "rewardDesc": "Enjoy HKDM rebate with your spending", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P85", "language": "zh-TW", "linkName": "更多資料", "rewardDesc": "簽賬可獲HKDM回贈", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}, {"linkUrl": "https://pfhcard.com/credit-card/", "cardName": "P85", "language": "zh-CN", "linkName": "更多资料", "rewardDesc": "签账可获HKDM回赠", "watermarkUrl": "https://static.prod.pfh-in.com/app/pfh_water_mark.png"}]',
    layout: 5,
    background_type: 1,
    background: 'https://static.prod.pfh-in.com/app/pfh_water_mark.png',
    background_thumbnail: 'https://static.prod.pfh-in.com/app/TitanCard.png',
    logo: 'https://static.prod.pfh-in.com/app/gl_logo.png',
    created_by: 'auto',
    created_date: '2024-10-08T08:50:20.197Z',
    last_modified_by: 'auto',
    last_modified_date: '2024-10-08T08:50:20.197Z',
    vip_level: 1,
  },
];

for (const json of jsonArray) {
  const cardInfos = JSON.parse(json.card_infos);

  for (const cardInfo of cardInfos) {
    cardInfo.linkUrl = 'https://double-pay.com/';
    cardInfo.watermarkUrl =
      'https://static.prod.pfh-in.com/app/gl_water_mark.png';
  }

  const sql = `-- ${json.program_name}
update pmp_access.merchant_program_configs
set
  card_infos = '${JSON.stringify(cardInfos)}',
  background = 'https://static.prod.pfh-in.com/app/gl_water_mark.png',
  logo = 'https://static.prod.pfh-in.com/app/dp_logo_black.png',
  last_modified_date = now ()
where
  id = '${json.id}'
  and program_name = '${json.program_name}';\n`;

  console.log(`${sql}`);
}
